### ISSUE TITLE
App Ops force close while Opening "Device" Card in "Descendant App"

### ISSUE THREAD

**Issue by darkestDark** [Descendant/rom_status#4]
Logcat...

SubSettings
Launching fragment com.android.settings.applications.appops.AppOpsSummary

AppOpsState
Unable to find info for package audioserver

AndroidRuntime
FATAL EXCEPTION: main
Process: com.android.settings, PID: 12813
java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
	at com.android.settings.applications.appops.AppOpsSummary$MyPagerAdapter.getPageTitle(AppOpsSummary.java:68)
	at android.support.v4.view.PagerTitleStrip.updateText(PagerTitleStrip.java:282)
	at android.support.v4.view.PagerTitleStrip.updateTextPositions(PagerTitleStrip.java:332)
	at android.support.v4.view.PagerTabStrip.updateTextPositions(PagerTabStrip.java:293)
	at android.support.v4.view.PagerTitleStrip$PageListener.onPageScrolled(PagerTitleStrip.java:484)
	at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1935)
	at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1904)
	at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1842)
	at android.support.v4.view.ViewPager.computeScroll(ViewPager.java:1802)
	at android.view.View.updateDisplayListIfDirty(View.java:19065)
	at android.view.View.draw(View.java:19935)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.updateDisplayListIfDirty(View.java:19073)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3331)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3135)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1479)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7378)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)

DEVICE: Leland
Rom: 1dot2

**Comment by Dil3mm4** [comment]
App-Ops has been dismissed as of now.
